### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by yys-abu** [openmedlab/MedFM#11]
File "C:\Anoconda\envs\pytorch\lib\site-packages\mmengine\config\config.py", line 1830, in __call__
    key, val = kv.split('=', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
['C:\\master\\configs\\vit-b_vpt\\1-shot_chest.py']

**Comment by MengzhangLI** [comment]
Hi, I think it is caused by your modification of config files or the typo of config files.

From your description, we can see your repo is based on master branch, which uses MMPretrain and MMEngine. 

You can check this config file, delete the empty line and try again. 

Best,

**Comment by yys-abu** [comment]
Hello, I printed out the value as follows:


['C:\\master\\configs\\swin-b_vpt\\1-shot_chest.py']



The complete error message is displayed as：
Traceback (most recent call last):
&nbsp; File "C:/master/tools/train.py", line 156, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "C:/master/tools/train.py", line 140, in main
&nbsp; &nbsp; args = parse_args()
&nbsp; File "C:/master/tools/train.py", line 64, in parse_args
&nbsp; &nbsp; args=parser.parse_args()
&nbsp; File "C:\Anoconda\envs\pytorch\lib\argparse.py", line 1768, in parse_args
&nbsp; &nbsp; args,argv=self.parse_known_args(args, namespace)
&nbsp; File "C:\Anoconda\envs\pytorch\lib\argparse.py", line 1799, in parse_known_args
&nbsp; &nbsp; namespace, args = self._parse_known_args(args, namespace)
&nbsp; File "C:\Anoconda\envs\pytorch\lib\argparse.py", line 2003, in _parse_known_args
&nbsp; &nbsp; start_index = consume_optional(start_index)
&nbsp; File "C:\Anoconda\envs\pytorch\lib\argparse.py", line 1944, in consume_optional
&nbsp; &nbsp; take_action(action, args, option_string)
&nbsp; File "C:\Anoconda\envs\pytorch\lib\argparse.py", line 1873, in take_action
&nbsp; &nbsp; action(self, namespace, argument_values, option_string)
&nbsp; File "C:\Anoconda\envs\pytorch\lib\site-packages\mmengine\config\config.py", line 1826, in __call__
&nbsp; &nbsp; key,val=kv.split('=', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)


Process finished with exit code 1



I don't know if you have encountered the same error. May I ask which file I should modify? As a beginner, I hope to receive guidance from my predecessors. If possible, I would like to add WeChat or QQ for consultation


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openmedlab/MedFM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月7日(星期一) 下午3:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openmedlab/MedFM] ValueError: not enough values to unpack (expected 2, got 1) (Issue #11)





 
Hi, I think it is caused by your modification of config files or the typo of config files.
 
From your description, we can see your repo is based on master branch, which uses MMPretrain and MMEngine.
 
You can check this config file, delete the empty line and try again.
 
Best,

**Comment by yys-abu** [comment]
Hello, thank you very much for replying to me. Due to code error display:


&nbsp; &nbsp; key,val=kv.split('=', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)



I print out the kV and display it as:


C:\master\configs\swin-b_vpt\1-shot_chest.py


Only one result


I still can't solve the problem after deleting empty lines from the config file. I don't know how to solve it.

yours sincerely




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openmedlab/MedFM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月7日(星期一) 下午3:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openmedlab/MedFM] ValueError: not enough values to unpack (expected 2, got 1) (Issue #11)





 
Hi, I think it is caused by your modification of config files or the typo of config files.
 
From your description, we can see your repo is based on master branch, which uses MMPretrain and MMEngine.
 
You can check this config file, delete the empty line and try again.
 
Best,

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.


Perhaps you use wrong command: https://github.com/open-mmlab/mmcv/issues/1840

I suggest you use default main branch first (create another conda environment), when everything is ok, then try to use master branch code.

Best,
