### ISSUE TITLE
Why does the code start slowly?

### ISSUE THREAD

**Issue by Yaphabates** [openmedlab/MedFM#12]
Hi, first of all thank you for the code. I would like to ask why my code is stuck for a long time before the training starts, is there anyone else who has the same problem as me?

**Comment by MengzhangLI** [comment]
If you use official baseline, I think you can ask MMPretrain and MMClassficiation: https://github.com/open-mmlab/mmpretrain.

Based on your current description, I can not draw a conclusion.
