### ISSUE TITLE
Finding dataset

### ISSUE THREAD

**Issue by dunpt** [openmedlab/MedFM#9]
Where can i find the datasets ? I don't find any instruction in this github to install the datasets.

**Comment by MengzhangLI** [comment]
You should find it if you read "A naive baseline and submission demo for the [Foundation Model Prompting for Medical Image Classification Challenge 2023 (MedFM)](https://medfm2023.grand-challenge.org/medfm2023/)."

Open the link, join the challenge and click the "dataset" in grand challenge website.

**Comment by dunpt** [comment]
thanks for your help.
